name: Manual Build Rule [cardpay-reward-programs]

on:
  pull_request:
  # push:
  #   branches:
  #     - "*"

jobs:
  test:
    name: Build & Lint
    runs-on: ubuntu-latest
    env:
      # we are running into heap out of memory issues with the linting--so
      # increasing the heap size to 8GB
      NODE_OPTIONS: --max-old-space-size=8192
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: volta-cli/action@v1
      - name: Set up yarn cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn --prefer-offline
      - run: yarn lint
  # build:
  #   name: Build and Push to ECR
  #   defaults:
  #     run:
  #       working-directory: ./packages/cardpay-reward-programs
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up env
  #       env:
  #         INPUT_ENVIRONMENT: ${{ github.event.inputs.environment }}
  #       run: |
  #         if [ "$INPUT_ENVIRONMENT" = "staging" ]; then
  #           echo "AWS_ACCESS_KEY_ID=${{ secrets.STAGING_REWARDS_ECR_WRITER_AWS_ACCESS_KEY}}" >> $GITHUB_ENV
  #           echo "AWS_SECRET_ACCESS_KEY=${{ secrets.STAGING_REWARDS_ECR_WRITER_AWS_ACCESS_SECRET }}" >> $GITHUB_ENV
  #     - name: Login to Amazon ECR
  #       id: login-ecr
  #       uses: aws-actions/amazon-ecr-login@v1

  #     - name: Build, tag, and push image to Amazon ECR
  #       env:
  #         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  #         ECR_REPOSITORY: flat_payment
  #         IMAGE_TAG: flat_payment
  #       run: |
  #         docker build --build-arg rule=FlatPayment -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
  #         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  #         echo "hi"

# on:
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: Deployment environment
#         required: false
#         default: staging
#       rule:
#         description: Rule name
#         required: true
#         default: FlatPayment
